name: Supposed version check

on:
  pull_request:
    types:
      - labeled
      - opened

jobs:
  enforce-label:
    name: Supposed version not exist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check major label
        id: check_pr_labels_major
        uses: Dreamcodeio/pr-has-label-action@master
        with:
          label: 'major'
      - name: Check minor label
        id: check_pr_labels_minor
        uses: Dreamcodeio/pr-has-label-action@master
        with:
          label: 'minor'
      - name: Check patch label
        id: check_pr_labels_patch
        uses: Dreamcodeio/pr-has-label-action@master
        with:
          label: 'patch'

      - name: Set found label
        run: |
          if [[ "${{ steps.check_pr_labels_major.outputs.hasLabel }}" ]]; then
            echo "CORRECT_LABEL=$(echo "major")" >> $GITHUB_ENV
          elif [[ "${{ steps.check_pr_labels_minor.outputs.hasLabel }}" ]]; then
            echo "CORRECT_LABEL=$(echo "minor")" >> $GITHUB_ENV
          elif [[ "${{ steps.check_pr_labels_patch.outputs.hasLabel }}" ]]; then
            echo "CORRECT_LABEL=$(echo "patch")" >> $GITHUB_ENV
          else
            echo "You need to specify correct label for your PR (major, minor or patch)"
            exit 1
          fi

      - name: Get supposed release version
        id: release_version
        run: |
          echo "::set-output name=release::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"

      - name: Calculate new version
        uses: actions-ecosystem/action-bump-semver@v1
        id: bump_semver
        with:
          current_version: ${{ steps.release_version.outputs.release }}
          level: ${{ env.CORRECT_LABEL }}

      - uses: mukunku/tag-exists-action@v1.0.0
        id: checkTag
        with:
          tag: 0.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/github-script@0.9.0
        if: ${{ steps.checkTag.outputs.exists }} = 'true'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `⚠️ Version \`${{ steps.bump_semver.outputs.new_version }}\` already exists ⚠️`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Exit if version already exists
        if: ${{ steps.checkTag.outputs.exists }} = 'true'
        run: |
          echo "::group::Version that should be released already exists in GitHub tags"
          exit 1

      - uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `*Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, New supposed version: \`${{ steps.bump_semver.outputs.new_version }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })