name: Enforce PR labels

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content_newer'
          skip_after_successful_duplicate: 'true'
  enforce-label:
    name: Labels check (major, minor or patch)
    needs: pre_job
    runs-on: ubuntu-latest
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Looking for any (major, minor or patch) label
        uses: yogevbd/enforce-label-action@2.1.0
        with:
          REQUIRED_LABELS_ANY: "major,minor,patch"
          REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label ['major','minor','patch']"

