name: Enforce PR labels

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened

jobs:
  enforce-label:
    name: Labels check (major, minor or patch)
    if: |
      contains(github.event.pull_request.labels.*.name, 'major') || contains(github.event.pull_request.labels.*.name, 'minor') || contains(github.event.pull_request.labels.*.name, 'patch')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Correct label found"


